spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:assets}
    username: ${DB_USERNAME:assets}
    password: ${DB_PASSWORD:assets}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


logging:
  level:
    org.hibernate: warn

server:
  port: ${PORT:9085}

security:
  api:
    key: ${API_KEY:my-secret-key}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
